# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='photo_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
