# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170312_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='photo_name',
            new_name='album_name',
        ),
    ]
