# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170312_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albums_img',
            field=models.ImageField(blank=True, null=True, upload_to='albums'),
        ),
    ]
