# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_album_albums_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_foto', models.CharField(blank=True, max_length=200, null=True)),
                ('file_foto', sorl.thumbnail.fields.ImageField(upload_to='images/%Y/%m/%d')),
            ],
            options={
                'db_table': 'foto',
            },
        ),
    ]
