# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='keywords',
            field=models.ManyToManyField(null=True, related_name='keywords', related_query_name='keyword', to='gallery.Keywords', verbose_name='Tags'),
        ),
    ]
