# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20170402_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='tag',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tags'),
        ),
    ]
