# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20170402_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='gallery.Keywords', verbose_name='Tags'),
        ),
    ]
