# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20170402_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='albums_img',
            field=models.ImageField(blank=True, upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
