# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20170405_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='keywords',
            field=models.ManyToManyField(related_name='albums', related_query_name='album', to='gallery.Keywords', verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='gallery.Album'),
        ),
    ]
